cache:
    paths:
        - app/frontend/node_modules
        - venv
        - app/frontend/package-lock.json
        - app/dist
install:
    stage: install
    script:
        - ./INSTALL
        - make install
build:
    stage: build
    script:
        - make build
unit test:
    stage: test
    script:
        - make test
