test:
    stage: build
    script:
        - ./INSTALL
        - make install
        - make build
        - make test-frontend
        - make test-backend
        - make validate-backend
    cache:
        paths:
            - app/frontend/node_modules
            - venv
            - app/frontend/package-lock.json
            - app/dist
