cache:
    paths:
        - app/frontend/node_modules
        - venv
        - app/frontend/package-lock.json
        - app/dist
build:
    stage: build
    script:
        - ./INSTALL
        - make install
        - make build
test vue:
    stage: test
    script:
        - make test-frontend
test flask:
    stage: test
    script:
        - make test-backend
